language: python
python:
- '2.7'
node_js:
- '6.3.1'
before_install:
- openssl aes-256-cbc -K $encrypted_c50ef8f16548_key -iv $encrypted_c50ef8f16548_iv
  -in uxgraph-client-secret.json.enc -out uxgraph-client-secret.json -d
# Check node/npm versions
- node -v
- npm -v

install: # setting 'install' to 'true' bypasses the install process: https://goo.gl/Az43Ut
# These commands help upgrade Node (See http://goo.gl/5wkGPK)
#- . $HOME/.nvm/nvm.sh
- nvm install stable
- nvm use stable

# Check node/npm versions
- node -v
- npm -v

- npm install

# Check node/npm versions once more
- node -v
- npm -v
#  true
script:


- npm run build.dev

deploy:
  provider: gae
  skip_cleanup: true
  keyfile: uxgraph-client-secret.json
  project: tessa3-uxgraph
  on: angular2-seed
