language: python
python:
- '2.7'
before_install:
- openssl aes-256-cbc -K $encrypted_c50ef8f16548_key -iv $encrypted_c50ef8f16548_iv
  -in uxgraph-client-secret.json.enc -out uxgraph-client-secret.json -d
deploy:
  provider: gae
  keyfile: "uxgraph-client-secret.json"
  project: "tessa3-uxgraph"
script: "main_test.py"
