language: python
python:
- '2.7'
before_install:
- openssl aes-256-cbc -K $encrypted_c50ef8f16548_key -iv $encrypted_c50ef8f16548_iv
  -in uxgraph-client-secret.json.enc -out uxgraph-client-secret.json -d
install: # setting 'install' to 'true' bypasses the install process: https://goo.gl/Az43Ut
  true
script:
- echo "No Script to run"
deploy:
  provider: gae
  #skip_cleanup: true
  keyfile: uxgraph-client-secret.json
  project: tessa3-uxgraph
