language: python
python:
- '2.7'
node_js:
- '6.3.1'
before_install:
- openssl aes-256-cbc -K $encrypted_c50ef8f16548_key -iv $encrypted_c50ef8f16548_iv
  -in uxgraph-client-secret.json.enc -out uxgraph-client-secret.json -d
install: # setting 'install' to 'true' bypasses the install process: https://goo.gl/Az43Ut
  true
script:
- node -v
- npm -v
- npm install --verbose
- npm run build.dev
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: uxgraph-client-secret.json
  project: tessa3-uxgraph
  on: angular2-seed
