runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /css
  static_dir: dist/prod/css

- url: /js
  static_dir: dist/prod/js

- url: /assets
  static_dir: dist/prod/assets

- url: /.*
  static_files: dist/prod/index.html
  upload: dist/prod/index.html
